version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: maven
  directory: "/angular-app"
  schedule:
    interval: monthly
  open-pull-requests-limit: 0
- package-ecosystem: maven
  directory: "/envtest"
  schedule:
    interval: monthly
  open-pull-requests-limit: 0
- package-ecosystem: maven
  directory: "/eslint"
  schedule:
    interval: monthly
  open-pull-requests-limit: 0
- package-ecosystem: maven
  directory: "/et4472"
  schedule:
    interval: monthly
  open-pull-requests-limit: 0
- package-ecosystem: maven
  directory: "/project"
  schedule:
    interval: monthly
  open-pull-requests-limit: 0
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/project"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    vue:
      patterns:
      - "@vue/*"
- package-ecosystem: npm
  directory: "/angular-app"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    angular:
      patterns:
      - "@angular/*"
      - "@angular-devkit/*"
- package-ecosystem: npm
  directory: "/eslint"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    typescript-eslint:
      patterns:
      - "@typescript-eslint/*"
      - "eslint"
- package-ecosystem: npm
  directory: "/vue-app"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    babel:
      patterns:
      - "@babel/*"
    vue:
      patterns:
      - "@vue/*"
- package-ecosystem: npm
  directory: "/vost"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    survey:
      patterns:
      - "survey-core"
      - "survey-react-ui"
