version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: maven
  directory: "/angular-app"
  open-pull-requests-limit: 0
- package-ecosystem: maven
  directory: "/envtest"
  open-pull-requests-limit: 0
- package-ecosystem: maven
  directory: "/eslint"
  open-pull-requests-limit: 0
- package-ecosystem: maven
  directory: "/et4472"
  open-pull-requests-limit: 0
- package-ecosystem: maven
  directory: "/project"
  open-pull-requests-limit: 0
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/project"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/angular-app"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/eslint"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
